# NOTE: this only works for 30 seconds before causing argus crash when encoding 60 FPS 2x 4k images

%YAML 1.2
---
name: color_converter
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12  # Increased for 60 FPS
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12  # Increased for 60 FPS
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: pool
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 19000000  # 19MB for 3552x3556 NV12
    num_blocks: 24  # Increased for 60 FPS
- name: color_converter_operator
  type: nvidia::isaac::tensor_ops::StreamConvertColorFormat
  parameters:
    output_type: "NV12"
    receiver: data_receiver
    transmitter: data_transmitter
    pool: pool
    input_adapter: global/adapter
    output_adapter: global/adapter
    output_name: "image"
    stream: global/stream
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: pool
    min_blocks: 1
---
name: global
components:
- name: adapter
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "VideoBuffer"
- name: stream
  type: nvidia::isaac::tensor_ops::TensorStream
  parameters:
    backend_type: "VPI"
    engine_type: "GPU"
- name: encoder_context
  type: nvidia::gxf::VideoEncoderContext
  parameters:
    scheduling_term: encoder_response/async_st
---
name: encoder
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12  # Increased for 60 FPS
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: encoder_request
  type: nvidia::gxf::VideoEncoderRequest
  parameters:
    input_frame: data_receiver
    inbuf_storage_type: 1
    profile: 0
    qp: 45  # Maximum QP for absolute speed (very low quality, maximum speed)
    hw_preset_type: 0  # Fast preset for speed over quality
    input_width: 3552
    input_height: 3556
    input_format: nv12
    config: custom
    iframe_interval: 10  # Maximum infrequent I-frames for absolute speed
    rate_control_mode: 0
    level: 14  
    videoencoder_context: global/encoder_context

---
name: encoder_response
components:
- name: output
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 6  # Increased for 60 FPS
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: output
    min_size: 1
- name: pool
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 0
    block_size: 15000000  # 15MB for compressed output
    num_blocks: 30  # Increased for 60 FPS
- type: nvidia::gxf::VideoEncoderResponse
  parameters:
    videoencoder_context: global/encoder_context
    output_transmitter: output
    outbuf_storage_type: 0
    pool: pool
- name: async_st
  type: nvidia::gxf::AsynchronousSchedulingTerm
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: pool
    min_blocks: 1
---
name: sink
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 8  # Increased for 60 FPS
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
    max_waiting_count: 1
    drop_waiting: false
---
name: connections
components:
- type: nvidia::gxf::Connection
  parameters:
    source: color_converter/data_transmitter
    target: encoder/data_receiver
- type: nvidia::gxf::Connection
  parameters:
    source: encoder_response/output
    target: sink/signal
---
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::EventBasedScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
- type: nvidia::gxf::JobStatistics
  parameters:
    clock: clock